@extends('frontend.layouts.app')
@section('content')
    @auth('customer')
        @include('frontend.dashboard.dashboard')
    @endauth
    @guest('customer')
        @include('frontend.auth.login')
    @endguest
@endsection