@extends('frontend.layouts.app')
@section('content')
    @auth
        @include('frontend.dashboard.dashboard')
    @endauth
    @guest
        @include('frontend.auth.login')
    @endguest
@endsection